## 视觉SLAM十四讲(高翔第二版)-试验 python版本


### 概述

本文主要是视觉SLAM试验的python版本，具体的书籍见book目录

### 3.2 实践:Eigen

In [1]:
import numpy as np

matrix_23 = np.array([[1, 2, 3], [4, 5, 6]])
matrix_23

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
for i in range(0, 2):
    for j in range (0, 3):
        print(matrix_23[i][j], end=" ")
    print()

1 2 3 
4 5 6 


In [12]:
v_3d = np.array([1, 2, 3])
np.matmul(matrix_23, v_3d)

array([14, 32])

In [32]:
matrix_33 = np.random.randint(1, 5, size=(3, 3))
matrix_33

array([[1, 3, 1],
       [1, 1, 2],
       [2, 4, 2]])

In [33]:
np.transpose(matrix_33)

array([[1, 1, 2],
       [3, 1, 4],
       [1, 2, 2]])

In [34]:
np.sum(matrix_33)

17

In [35]:
np.trace(matrix_33)

4

In [36]:
10 * matrix_33

array([[10, 30, 10],
       [10, 10, 20],
       [20, 40, 20]])

In [38]:
np.linalg.inv(matrix_33)

array([[-3. , -1. ,  2.5],
       [ 1. , -0. , -0.5],
       [ 1. ,  1. , -1. ]])

In [39]:
np.linalg.det(matrix_33)

2.0

In [45]:
np.linalg.eig(matrix_33)

(array([ 5.51604587, -0.29756642, -1.21847945]),
 array([[-0.46393107, -0.91538272,  0.69265906],
        [-0.44258071,  0.31051093, -0.62954589],
        [-0.76739186,  0.25623708,  0.35198778]]))

In [48]:
matrix_nn = np.random.randint(1, 10, size=(50, 50))
matrix_nn

array([[5, 8, 3, ..., 9, 4, 9],
       [9, 1, 1, ..., 3, 2, 1],
       [8, 4, 9, ..., 4, 8, 7],
       ...,
       [2, 6, 8, ..., 6, 1, 3],
       [1, 4, 6, ..., 6, 9, 2],
       [5, 6, 6, ..., 3, 1, 1]])

In [57]:
v_nd = np.random.randint(1, 10, size=50)
print(v_nd)
print(v_nd.shape)

[9 1 8 8 3 2 2 8 5 7 1 8 1 3 5 8 4 3 8 4 1 6 5 1 8 3 9 7 4 8 8 6 8 3 5 9 2
 6 3 1 6 8 8 4 5 8 4 3 2 5]
(50,)


In [60]:
import time

start = time.time()
x = np.matmul(np.linalg.inv(matrix_nn), v_nd)
end = time.time()
print(end - start)
print(x.shape)
print(x)

0.04220008850097656
(50,)
[ 0.40453479  0.21081333  0.15775043  0.13305694  0.36762567  0.2496835
  0.03652863 -0.11186222  0.37185061 -0.09419048  0.21041235 -0.52965271
 -0.27828885  0.11931321  0.29507741  0.56328278 -0.38263062  0.03736046
  0.15515711 -0.45983229 -0.49846434 -0.21536684  0.30243571  0.32614368
  0.08867983  0.14434343  0.02491098 -0.14299174 -0.19563341 -0.02892861
  0.08015624  0.16616452 -0.09386843 -0.23505035 -0.10921711 -0.07164552
 -0.31599832  0.23173916  0.15070496 -0.08802361 -0.05365585  0.07396251
 -0.36141757 -0.22000057  0.71672327 -0.11157175 -0.28157426  0.35841282
 -0.47766384  0.29592338]


In [62]:
start = time.time()
q, r = np.linalg.qr(matrix_nn)
x = np.linalg.solve(r, np.dot(q.T, v_nd))
end = time.time()
print(end -start)
print(x.shape)
print(x)

0.04405784606933594
(50,)
[ 0.40453479  0.21081333  0.15775043  0.13305694  0.36762567  0.2496835
  0.03652863 -0.11186222  0.37185061 -0.09419048  0.21041235 -0.52965271
 -0.27828885  0.11931321  0.29507741  0.56328278 -0.38263062  0.03736046
  0.15515711 -0.45983229 -0.49846434 -0.21536684  0.30243571  0.32614368
  0.08867983  0.14434343  0.02491098 -0.14299174 -0.19563341 -0.02892861
  0.08015624  0.16616452 -0.09386843 -0.23505035 -0.10921711 -0.07164552
 -0.31599832  0.23173916  0.15070496 -0.08802361 -0.05365585  0.07396251
 -0.36141757 -0.22000057  0.71672327 -0.11157175 -0.28157426  0.35841282
 -0.47766384  0.29592338]
